spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/alioth
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
firebase:
  api-url: "https://fcm.googleapis.com/v1/projects/alioth-fcm/messages:send"
  config-path: "/firebase/fcm-certification.json"


cloud:
  aws:
    s3:
      bucket: aliothsss #<S3 버킷 이름>
    credentials:
      access-key: AKIA2PG2M5INGTJHHVC6 # <저장해놓은 액세스 키>
      secret-key: 8tavJ9yR/INxi4I0USyRAISRm1Q/OiQzgKieFJ9z # <저장해놓은 비밀 액세스 키>
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false