spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/alioth
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
firebase:
  api-url: "https://fcm.googleapis.com/v1/projects/aliothfcm/messages:send"
  config-path: "/firebase/aliothfcm-firebase-adminsdk-fye6y-a496184283.json"
