apiVersion: apps/v1
kind: Deployment
metadata:
  name: alioth-deployment
spec:
  selector:
    matchLabels:
      app: alioth-deployment
  template:
  # pod의 네임
    metadata:
      labels:
        app: alioth-deployment
    spec:
      containers:
      - name: alioth-server
        image: 719865047578.dkr.ecr.ap-northeast-2.amazonaws.com/alioth-hub:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 700m
      - name: alioth-statistics
        image: 719865047578.dkr.ecr.ap-northeast-2.amazonaws.com/alioth-stat:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 250m
          limits:
           cpu: 700m
