apiVersion: apps/v1
kind: Deployment
metadata: 
  name: alioth-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alioth-gateway
  template:
  # pod의 네임
    metadata:
      labels:
        app: alioth-gateway
    spec:
      containers:
      - name: alioth-gateway
        image: 719865047578.dkr.ecr.ap-northeast-2.amazonaws.com/alioth-hub:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alioth-gateway-service
spec:
# ClusterIp는 클러스터 내부에서만 접근 가능한 service를 생성
  type: ClusterIP
  ports:
  - name : http
    port: 80
    targetPort: 8080
  selector:
    app: alioth-gateway
